plugins:
  services:
    - 'lib.service.TurboVNCServerCustom'



old_client:
  queue_entries:
    ssh:
      SCHEDULER : "SSH"

  vnc_entries:
    default_fluxbox_virtualgl:
      SERVICE : "VNC_default"
      SERVICE.COMMAND : "TurboVNC"
      SERVICE.COMMAND.WM : "Fluxbox_with_virtualgl"
    v001_fluxbox_prview_5.5.1:
      SERVICE : "VNC_v001"
      SERVICE.COMMAND : "TurboVNC"
      SERVICE.COMMAND.WM : "Fluxbox_paraview_5.5.1"
    2019_fluxbox:
      SERVICE : "VNC_latest_stack"
      SERVICE.COMMAND : "TurboVNC"
      SERVICE.COMMAND.WM : "Fluxbox"
    2019_opnbx:
      SERVICE : "VNC_latest_stack"
      SERVICE.COMMAND : "TurboVNC"
      SERVICE.COMMAND.WM : "Openbox"
    2019_opnbx_prview_5.5.2:
      SERVICE : "VNC_latest_stack"
      SERVICE.COMMAND : "TurboVNC"
      SERVICE.COMMAND.WM : "Openbox+viz+tools+preloaded"



defaults:
  TOP:
    SERVICE :
#      VNC_v002 :
#        description : "TurboVNC stack from ba modules "
#        COMMAND :
#          TurboVNC:
#            description : "TurboVNC session from stack in modules  "
#            substitutions :
#              SETUP: |
#                module use /gpfs/work/DATA/spack/v002/RCM_spack_deploy/deploy/base_spack_devel/spack/share/spack/modules/linux-centos7-x86_64
#                module use /gpfs/work/DATA/spack/v002/RCM_spack_deploy/deploy/rcm_chained/spack/share/spack/modules/linux-centos7-x86_64
#                module use /gpfs/work/DATA/spack/v002/RCM_spack_deploy/deploy/insitu_chained/spack/share/spack/modules/linux-centos7-x86_64
#                module load xdpyinfo
#                module load virtualgl
#
#
#            WM :
#              Fluxbox :
#                description : "Start Fluxbox as Window manager for the VNC session (lightest choice)"
#                substitutions :
#                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.fluxbox"
#                  WM_SETUP: |
#                    module load fluxbox
#                    module load pcmanfm
#                    module load lxde-lxterminal


      VNC_19_11 :
        description : "TurboVNC stack /gpfs/work/cin_rcmmgr/spack/RCM_spack_deploy/deploy "
        COMMAND :
          description : "TurboVNC sw stack with paraview 5.5.2 visit, vtk, xdiff3, openbox, located in /gpfs/work/cin_rcmmgr/spack/RCM_spack_deploy/deploy "
          TurboVNC:
            substitutions :
              SETUP: |
                module use /gpfs/work/cin_rcmmgr/spack/RCM_spack_deploy/deploy/rcm_chained/modules/linux-centos7-haswell
                module use /gpfs/work/cin_rcmmgr/spack/RCM_spack_deploy/deploy/paraview_chained_rcm/modules/linux-centos7-haswell
                module load xdpyinfo
                module load virtualgl


            WM :
              Openbox :
                description : "Start LXDE Openbox as Window manager, no viz module pre-loaded, All nodes"
                substitutions :
                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.openbox"
                  WM_SETUP: |
                    module load openbox
                    module load pcmanfm
                    module load lxde-lxterminal
                    module load tint2
                    module load gpicview
                    module load leafpad


              Fluxbox :
                description : "Start Fluxbox as Window manager, no viz module pre-loaded, All nodes "
                substitutions :
                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.fluxbox"
                  WM_SETUP: |
                    module load fluxbox
                    module load pcmanfm
                    module load lxde-lxterminal



              Openbox_viztools_preloaded:
                description : "Start LXDE Openbox, preload viz modules (GPU nodes only)"
#                description : |
#                  Start LXDE Openbox, preload viz modules (GPU nodes only)
#                  paraview (5.5.2)
#                  visit (3.0.1)
#                  vtk (8.1.2)
#                  gnuplot (5.2.5)
#                  kdiff3
#                  inage-magick



                substitutions :
                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.openbox"
                  WM_SETUP: |
                    module load openbox
                    module load pcmanfm
                    module load lxde-lxterminal
                    module load tint2
                    module load gpicview
                    module load image-magick
                    module load leafpad
                    module load kdiff3
                    module load gnuplot
                    module load visit
                    module load paraview



      VNC_legacy :
        description : "TurboVNC stack from ba modules "
        COMMAND :
          description : "TurboVNC session from standard modules  "
          TurboVNC:
            description: "TurboVNC session from stack in modules  "
            substitutions:
              SETUP: |
                module load /cineca/prod/spack/v001/RCM_spack_deploy/deploy/galileo_dev00/insitu01/spack/share/spack/modules/linux-centos7-x86_64/virtualgl/2.5.2-gcc-7.3.0-cs 



            WM:
              #description: "Start Fluxbox as Window manager session with virtualgl preloaded" 
              KDE :
                description : "Start KDE  as Window manager REQUIRE SSH scheduler (login only)" 
                substitutions :
                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.kde"
                  WM_SETUP: |
                    module load fluxbox


              Fluxbox :
                description : "Start Fluxbox as Window manager (lightest choice)" 
                substitutions :
                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.fluxbox"
                  WM_SETUP: |
                    module load fluxbox
                    module load pcmanfm
                    #module load profile/visual



#              Fluxbox_bare :
#                description : "Start Fluxbox as Window manager DOES NOT WORK ON gll_usr_prod" 
#                substitutions :
#                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.fluxbox"
#                  WM_SETUP: |
#                    module load fluxbox
#                    module load pcmanfm


#      VNC_v001 :
#        description : "using modules in /cineca/prod/spack/v001/RCM_spack_deploy/deploy/galileo_dev00/insitu01/spack/share/spack/modules/linux-centos7-x86_64 "
#        COMMAND :
#          description : "TurboVNC sw stack, paraview_5.5.1 from /galileo/prod/spack/v001"
#          TurboVNC:
#            description : "TurboVNC and other modules from /galileo/prod/spack/v001/RCM_spack_deploy/deploy/galileo_dev00/install/linux-centos7-x86_64/gcc-7.3.0 "
#            substitutions :
#              SETUP: |
#                module use /cineca/prod/spack/v001/RCM_spack_deploy/deploy/galileo_dev00/insitu01/spack/share/spack/modules/linux-centos7-x86_64
#                module load xdpyinfo
#                module load virtualgl


#            WM :
#              Fluxbox_paraview_5.5.1 :
#                description : "Start Fluxbox as Window manager for the VNC session (lightest choice)"
#                substitutions :
#                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.fluxbox"
#                  WM_SETUP: |
#                    module load fluxbox
#                    module load pcmanfm
#                    module load lxde-lxterminal
#                    module load paraview


