plugins:
  services:
    - 'lib.service.TurboVNCServerCustom'



old_client:
  queue_entries:
    ssh:
      SCHEDULER : "SSH"

  vnc_entries:
    default_fluxbox_virtualgl:
      SERVICE : "VNC_default"
      SERVICE.COMMAND : "TurboVNC"
      SERVICE.COMMAND.WM : "Fluxbox_with_virtualgl"
    v001_fluxbox_prview_5.5.1:
      SERVICE : "VNC_v001"
      SERVICE.COMMAND : "TurboVNC"
      SERVICE.COMMAND.WM : "Fluxbox_paraview_5.5.1"
    2019_fluxbox:
      SERVICE : "VNC_latest_stack"
      SERVICE.COMMAND : "TurboVNC"
      SERVICE.COMMAND.WM : "Fluxbox"
    2019_opnbx:
      SERVICE : "VNC_latest_stack"
      SERVICE.COMMAND : "TurboVNC"
      SERVICE.COMMAND.WM : "Openbox"
    2019_opnbx_prview_5.5.2:
      SERVICE : "VNC_latest_stack"
      SERVICE.COMMAND : "TurboVNC"
      SERVICE.COMMAND.WM : "Openbox+viz+tools+preloaded"



defaults:
  TOP:
    SERVICE :
#      VNC_v002 :
#        description : "TurboVNC stack from ba modules "
#        COMMAND :
#          TurboVNC:
#            description : "TurboVNC session from stack in modules  "
#            substitutions :
#              SETUP: |
#                module use /gpfs/work/DATA/spack/v002/RCM_spack_deploy/deploy/base_spack_devel/spack/share/spack/modules/linux-centos7-x86_64
#                module use /gpfs/work/DATA/spack/v002/RCM_spack_deploy/deploy/rcm_chained/spack/share/spack/modules/linux-centos7-x86_64
#                module use /gpfs/work/DATA/spack/v002/RCM_spack_deploy/deploy/insitu_chained/spack/share/spack/modules/linux-centos7-x86_64
#                module load xdpyinfo
#                module load virtualgl
#
#
#            WM :
#              Fluxbox :
#                description : "Start Fluxbox as Window manager for the VNC session (lightest choice)"
#                substitutions :
#                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.fluxbox"
#                  WM_SETUP: |
#                    module load fluxbox
#                    module load pcmanfm
#                    module load lxde-lxterminal


      VNC-1911 :
        description : |
          TurboVNC server session based on spack built, linux-centos7-haswell sw stack, provided by:
            module use /gpfs/work/cin_rcmmgr/spack/RCM_spack_deploy/deploy/rcm_chained/modules/linux-centos7-haswell
            module use /gpfs/work/cin_rcmmgr/spack/RCM_spack_deploy/deploy/paraview_chained_rcm/modules/linux-centos7-haswell


        COMMAND :
          description : |
            This TurboVNC sw stack preloads the following modules:
              turbovnc
              xdpyinfo
              vrtualgl
            provides modules:
              paraview 5.5.2 --> vglrun paraview
              visit (3.0.1) --> vglrun visit
              vtk (8.1.2) --> vglrun vtkpython
              gnuplot (5.2.5)
              kdiff3
              image-magick



          TurboVNC:
            substitutions :
              SETUP: |
                module use /gpfs/work/cin_rcmmgr/spack/RCM_spack_deploy/deploy/rcm_chained/modules/linux-centos7-haswell
                module use /gpfs/work/cin_rcmmgr/spack/RCM_spack_deploy/deploy/paraview_chained_rcm/modules/linux-centos7-haswell
                module load xdpyinfo
                module load virtualgl


            WM :
              Openbox :
                description : |
                  The VNC session start LXDE Openbox as Window manager,
                   should be supported on All nodes ( login, cpu-only, cpu+gpu)
                   preloads following additional modules:
                    module load openbox
                    module load pcmanfm
                    module load lxde-lxterminal
                    module load tint2
                    module load gpicview
                    module load leafpa


                substitutions :
                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.openbox"
                  WM_SETUP: |
                    module load openbox
                    module load pcmanfm
                    module load lxde-lxterminal
                    module load tint2
                    module load gpicview
                    module load leafpad


              Fluxbox :
                description : |
                  The VNC session start Fluxbox  as Window manager,
                   should be supported on All nodes ( login, cpu-only, cpu+gpu)
                   preloads following additional modules:
                    module load fluxbox
                    module load pcmanfm
                    module load lxde-lxterminal

                substitutions :
                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.fluxbox"
                  WM_SETUP: |
                    module load fluxbox
                    module load pcmanfm
                    module load lxde-lxterminal



              Openbox_preload:
#                description : "Start LXDE Openbox, preload viz modules (GPU nodes only)"
                description : |
                  The VNC session start LXDE Openbox as Window manager,
                  is supported only on nodes with GPU
                  preloads openbox modules:
                    module load openbox pcmanfm lxde-lxterminaltint2 gpicview leafpad
                  these gui tools:
                    module load gnuplot (5.2.5)
                    module load kdiff3
                    module load image-magick
                  as well these modules for Opengl appliacations that require vglrun prepend:
                    module load paraview (5.5.2) --> vglrun paraview
                    module load visit (3.0.1) --> vglrun visit
                    vmodule load vtk (8.1.2) --> vglrun vtkpython




                substitutions :
                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.openbox"
                  WM_SETUP: |
                    module load openbox
                    module load pcmanfm
                    module load lxde-lxterminal
                    module load tint2
                    module load gpicview
                    module load image-magick
                    module load leafpad
                    module load kdiff3
                    module load gnuplot
                    module load visit
                    module load paraview



      VNC_legacy :
        description : "TurboVNC stack from ba modules "
        COMMAND :
          description : "TurboVNC session from standard modules  "
          TurboVNC:
            description: "TurboVNC session from stack in modules  "
            substitutions:
              SETUP: |
                module load /cineca/prod/spack/v001/RCM_spack_deploy/deploy/galileo_dev00/insitu01/spack/share/spack/modules/linux-centos7-x86_64/virtualgl/2.5.2-gcc-7.3.0-cs 



            WM:
              #description: "Start Fluxbox as Window manager session with virtualgl preloaded" 
              KDE :
                description : "Start KDE  as Window manager REQUIRE SSH scheduler (login only)" 
                substitutions :
                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.kde"
                  WM_SETUP: |
                    module load fluxbox


              Fluxbox :
                description : "Start Fluxbox as Window manager (lightest choice)" 
                substitutions :
                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.fluxbox"
                  WM_SETUP: |
                    module load fluxbox
                    module load pcmanfm
                    #module load profile/visual



#              Fluxbox_bare :
#                description : "Start Fluxbox as Window manager DOES NOT WORK ON gll_usr_prod" 
#                substitutions :
#                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.fluxbox"
#                  WM_SETUP: |
#                    module load fluxbox
#                    module load pcmanfm


#      VNC_v001 :
#        description : "using modules in /cineca/prod/spack/v001/RCM_spack_deploy/deploy/galileo_dev00/insitu01/spack/share/spack/modules/linux-centos7-x86_64 "
#        COMMAND :
#          description : "TurboVNC sw stack, paraview_5.5.1 from /galileo/prod/spack/v001"
#          TurboVNC:
#            description : "TurboVNC and other modules from /galileo/prod/spack/v001/RCM_spack_deploy/deploy/galileo_dev00/install/linux-centos7-x86_64/gcc-7.3.0 "
#            substitutions :
#              SETUP: |
#                module use /cineca/prod/spack/v001/RCM_spack_deploy/deploy/galileo_dev00/insitu01/spack/share/spack/modules/linux-centos7-x86_64
#                module load xdpyinfo
#                module load virtualgl


#            WM :
#              Fluxbox_paraview_5.5.1 :
#                description : "Start Fluxbox as Window manager for the VNC session (lightest choice)"
#                substitutions :
#                  WM_COMMAND: "-xstartup ${RCM_HOME}/bin/config/xstartup.fluxbox"
#                  WM_SETUP: |
#                    module load fluxbox
#                    module load pcmanfm
#                    module load lxde-lxterminal
#                    module load paraview


