config:
  build_stage:
  - /dev/shm/$user
  - /scratch_local/$user
  - $tempdir

  source_cache: "{{DEPLOY_SPACK_CACHE}}"
  install_tree: "{{DEPLOY_SPACK_INSTALL}}"
  module_roots:
    tcl: "{{DEPLOY_SPACK_MODULES}}"



